branch-defaults:
  main:
    environment: stock-research-prod
    group_suffix: null
  develop:
    environment: stock-research-staging
    group_suffix: null

global:
  application_name: stock-research-system
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application

deploy:
  artifact: deploy.zip